name: "Auto Assign"

on:
  pull_request:
    branches:
      - "!dev"

jobs:
  assign:
    name: Sync PR
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: ".github/auto-assign.yml"
